services:
- docker
install: make docker-login build
stages:
- name: publish
  if: type != pull_request
jobs:
  include:
  - stage: publish
    name: Publish image
    script:
    - make docker-login publish
env:
  global:
  - secure: jCic7NPIRKG054xdAXC3SZ9c1GewnHGPMb/8IXTWo+WcHK6OA+pqj1SHJm90V1tyJmG1KOxXGshN4vJcCtx1Mb0GL+lCI0gVRdbneN6TfMxvOzVhSnzSz9C3vRXRUUslFRscSZiTzrvqsiUbulLPWLa34tNz4l1vXxI6RzlRFzI3aAcCC0XFOj5YuBOrKSXJ/Wf5a/0R/WlIMKHAsCsqg1+/TLfIi+e0XQuuMJwQYMSwxUJZF6ZgxNZeKtkS+0THKO7N1XtxsWr0O9y60b689GevxVuB1dCXMKng9xvZSiHMLK4fxji2Ts6ZrHoI8Klo+kr0R51YfYx+gBqdMqVsTrMFccQEB2s4vFLQKXDNdZXzjSQ9P2y+RWgmpxrP5+/gz14MA9oLlt5YkfdKbpPylQ1ZNnV6tiOJT96qPiYVeEIS11xqFJ6eIntYFqXZ3O1dixZhO2ADRuCC5ZNLw4M7NPGVeegiYYtEheuolWIAo8aq6HuBlo1zjzFZeChrMSBfYoZiXXoSozeaJLJlK4z7Jj6XcQ+G4lu0b8cMYHTBlrwGa3BJMS6savp8ZOcDpNhO9VED6LeKwAD9bm86BNAgoKWKisYxdw7a0O7aEwMV5KKMQnS2kGWlPmNYxM5CoMvrE9aCjUMO0ZMbi7tznIp2LRXLgzKF66AYMyiSknaqFXc=
  - secure: E42mBmJNwJVJ76SVWC5zo9DfA9xW6d0A/jXQyz3XsWbnYUFKnToXl3RAskrEj1Zh7gAFlDxrZdjSP2dcs5UJYTWSV8La/Op/Z0YA02CPM2Ysf/BpJQAPBgzQbNPsBu8dP6NkmI4HitHuCP5vItX3gUZ/FJNMn1+JT/5zo018epe9d4y7oferlbIk4UEdCH0FBX3LOZ2V6OEvlnVBhuBsLVkMy4g/BWqwSKQdQ2Tc3uL2pAyq9AT+ztwGmE9nQSstMhyuaSQPw/pmG0YoFTHzmrWFBOGvd5Z0gdLhHwDNi8xcL/F/wZV7L4NvBMwBLYupKVY3kwPCBIA88wMSdZsV1PcwRJC5t2nD2YizuHcj2QMAErlgiHW5cdrReLfD+NM8wgNvjQldlkf7Yz2M76ufxQXH6LW7Mxu11BftaqYAl4OhU0BCjwtUvU2S0Gmbed7MCeLn30SZJkdVwxrUHc/00sYPZOux4mq2JewfXmuRWcAIPxs2tjJjGqOMOAbeu7XOISSwhuo0FU5uUIiuG9o61QFLLxhD08fnwpHbFfKNII8mQ/+7M5a0v6HgMHrVcCOq+uchv5jXlpXzlMzgiqY4g1bbtXa9nZ2Sdrb27ZKzKeggaZd7Zg830ML74TVWoIxNw1RfECfIuaC/TOEWjW7PwoLHLlKNwUkt1q498TgcBNk=
